**Pytorch tutorial**

In [54]:
import torch
device='cuda' if torch.cuda.is_available() else "cpu"
import torch
my_tensor=torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,device='cpu',requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [55]:
print(my_tensor.dtype)
x=torch.eye(5,5)
print(x)
x=torch.arange(start=0,end=5,step=1)
print(x)
x=torch.rand((3,3))
print(x)
x=torch.linspace(start=0.1,end=1,steps=10)
print(x)
x=torch.diag(torch.ones(5))
print(x)

torch.float32
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([[0.8549, 0.1403, 0.8772],
        [0.5876, 0.9676, 0.9477],
        [0.2639, 0.5852, 0.8966]])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [56]:
import torch

x = torch.arange(4)
print(x.long())
print(x.float())
print(x.double())
import numpy as np
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)
print(type(tensor))

tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)
<class 'torch.Tensor'>


Tensor Math and Comparison Operations

In [57]:
z=torch.empty(3)
#print(z)
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
# Addition
torch.add(x,y,out=z)
z2=torch.add(x,y)
z=x+y
#inplace operations
t=torch.zeros(3)
t+=x
#Exponentiation element wise pow of 2
z=x.pow(2)
z=x>0
#print(z)

# Matrix Multiplication
x=torch.rand((2,2))
y=torch.rand((2,2))
z=torch.mm(x,y)
#print(z)
z=x.mm(y)
#print(z)
# Matrix exponential
matrix_exp=torch.rand(5,5)
matrix_exp.matrix_power(3)
#print(matrix_exp)

# Element wise multi
z=x*y
#print(z)
# Batch wise multiplication
batch=32
n=10
m=20
p=30
tensor1=torch.rand(batch,n,m)
tensor2=torch.rand(batch,m,p)
o=torch.bmm(tensor1,tensor2)
#print(o.shape)

# Broadcasting (Automatic expansion)

x1=torch.rand((5,5))
x2=torch.rand((1,5))
z=x1-x1

# Other operations
x=torch.rand((3,2))
sum=torch.sum(x,dim=0)
#print(sum)
value,index=torch.max(x,dim=0)
abs=torch.abs(x)
#print(torch.argmin(x,dim=0))
mean_x=torch.mean(x.float(),dim=0)
#print(mean_x)
z=torch.sort(y,dim=0,descending=True)
#print(z)
x=torch.tensor([[22,10,0.8],[-0.6,7,8]])
x=torch.clamp(x,min=0,max=10)
#print(x)
x=torch.tensor([1,0,1,1,1],dtype=torch.bool)
z=torch.all(x)
print(z)

tensor(False)


**Indexing**

In [63]:
x=torch.arange(10)
#print(x[(x>2)&(x>5)])
#print(x[x.remainder(2)==0])

# Useful Operations
print(torch.where(x>5,x,x*2)) # Later is satisfied else option 1
x=torch.arange(9)
x=x.view(3,3) # View and reshape similar
#print(x)

y=x.t()
#print(y)
y=y.reshape(9)
print(y)

x1=torch.rand((2,5))
x2=torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)


tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
torch.Size([4, 5])


**Permute**

In [73]:
batch=64
x=torch.rand((batch,3,4))
z=x.permute(0,2,1)
z1=x.permute(1,0,2)
x=torch.rand((3,4))
z2=x.t()
print(z1.shape)
print(z.shape)
print(z2.shape)

torch.Size([3, 64, 4])
torch.Size([64, 4, 3])
torch.Size([4, 3])


**Squeeze and Unsqueeze**

In [77]:
x=torch.rand(10)
print(x)
z=x.unsqueeze(0) # Matrix format...Basically a list into matrix . For 0 it means columns increase
print(z)
z=x.unsqueeze(1)
print(z) # Row wise Unsqueeze

tensor([0.4150, 0.7162, 0.7118, 0.2903, 0.8003, 0.8989, 0.4032, 0.3620, 0.6444,
        0.6164])
tensor([[0.4150, 0.7162, 0.7118, 0.2903, 0.8003, 0.8989, 0.4032, 0.3620, 0.6444,
         0.6164]])
tensor([[0.4150],
        [0.7162],
        [0.7118],
        [0.2903],
        [0.8003],
        [0.8989],
        [0.4032],
        [0.3620],
        [0.6444],
        [0.6164]])
